### ISSUE TITLE
New Design Requests

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#20]
- [x] Screen for when a user logs in and has no upcoming harvests
- [x] Submit new harvest screen
- [x] Edit plot screen

**Comment by alexgleason** [comment]
> **Screen for when a user logs in and has no upcoming harvests**

![manage-screen-empty](https://user-images.githubusercontent.com/3639540/32618408-a66e80c6-c545-11e7-8eda-7bff1ce999e0.png)

My inspiration for this design is elementary OS's "[welcome screen](https://elementary.io/docs/human-interface-guidelines#welcome-screen)" design standard. Example below:

![welcome-screen](https://user-images.githubusercontent.com/3639540/32618597-2d52a89c-c546-11e7-869e-1e4348bbe69f.png)

elementary OS has a fantastic HIG and it's worth reading their recommendations for [first launch experience](https://elementary.io/docs/human-interface-guidelines#first-launch-experience) and [welcome screen](https://elementary.io/docs/human-interface-guidelines#welcome-screen).

This was a quick sketch, but down the line we may want to come back and also add "manage plots" or "manage gardens" as extra options alongside "submit an order". For now they're configured under the "manage" nav at the top. I have other ideas about that too though, such as only prompting for the creation of those items when the app detects that they user doesn't have any made.

**Comment by marykatefain** [comment]
This looks good! Thanks!

**Comment by alexgleason** [comment]
> **Submit new harvest screen**

Here's a mockup for a "submit new order" screen.

![create-order](https://user-images.githubusercontent.com/3639540/32630908-69dc82a8-c56c-11e7-8de8-6c7376a0ce11.png)

Certain aspects of this design I don't consider to be final, such as the colors of the selected crops and the "add another" button. These are things we can adjust after it's coded, so I'd say go ahead.

I envision the input boxes having some special functionality. The date inputs should pop up a calendar to select from, and the "select a plot" should show the relevant plots organized by the garden they belong to.

**Comment by marykatefain** [comment]
This looks great! Thanks!!

**Comment by marykatefain** [comment]
I think there should be a submit order button on the new order design.

**Comment by alexgleason** [comment]
A submit order button, what do you mean? You mean the users can't just shake their phone and make it submit? :stuck_out_tongue_winking_eye: 

My mistake. I'll update the design after completing the others, unless you implement something first.

**Comment by marykatefain** [comment]
I'm not ruling out the shaking.... :P

**Comment by alexgleason** [comment]
Here's the edit plot screen. Submit button intentionally omitted.

![edit-a-plot](https://user-images.githubusercontent.com/3639540/32695350-40342624-c727-11e7-8de6-9875dd19c20c.png)

**Comment by alexgleason** [comment]
Android seems to like putting "submit" buttons in the floating navbar. My intuition is to do something like this, but I'm not totally sure. Some examples below.

My only hesitation is that icons without labels add complexity. We can't assume a user will understand them. For instance, I wrote the word BACK aside the back arrow because user testing shows that people a way more likely to open a hamburger menu that actually says the word "MENU" beside it. You have to really spell it out to people. It's kinda like how plain text emails perform better than fancy templates; the reality is that pretty design often overcomplicates things for the user.

![screenshot_20171112-212747](https://user-images.githubusercontent.com/3639540/32707258-8a9d7e26-c7f0-11e7-8e46-d2a4388b5f82.png)
![screenshot_20171112-212731](https://user-images.githubusercontent.com/3639540/32707259-8aac249e-c7f0-11e7-81e6-c472963126df.png)

**Comment by marykatefain** [comment]
RE: edit plot design:

How do users delete crops? Also we don't need the tap to select stuff here.

**Comment by alexgleason** [comment]
I think we can close this one. Let's open new, more detailed issues if necessary.
