### ISSUE TITLE
Navbar dropdown menu improvements (and on mobile)

### ISSUE THREAD

**Issue by alexgleason** [HarvestHub/GardenHub#22]
I kinda took the idea from Simple's UI. Here's what Simple's UI looks like.

![screenshot from 2017-11-09 11 47 03](https://user-images.githubusercontent.com/3639540/32617759-e07284b8-c543-11e7-8947-f107ce33dc23.png)

I think we could take some inspiration from it. Something to keep in mind is that Simple's UI was meant for desktop (using a mouse cursor) while we're designing GH mobile first (meant for thumbs). Having big buttons (as they are) is probably good so it's thumb-sized.

For reference this is what we currently have.

![screenshot from 2017-11-09 11 51 14](https://user-images.githubusercontent.com/3639540/32617922-4e757ab0-c544-11e7-815b-bd502d658fa0.png)

I'm thinking at the very least we can:

1. Remove the dividers, they aren't needed.
2. Use a more plain bg color like white or gray, with the text being purple.
3. Have hover states that invert the item color.
4. Use some slightly rounded corners and a nice drop shadow.
5. Add that little arrow at the top. It makes a big difference. It conveys where the dropdown originated from.

**Comment by marykatefain** [comment]
![nav_improvements](https://user-images.githubusercontent.com/17955536/32637291-f674b50e-c586-11e7-8dd2-d4c6733263aa.png)

Latest push did drop shadow, border radius, and the little arrow. Although I'm not sure I agree that many of the other things work well on mobile... I'll look at some good mobile navs and see what works for others. 

I can't figure out how to make a drop shadow on the arrow because of the trick I used to make them....  It's essentially just borders. Is there a better way to make those arrows then this css trick?

**Comment by marykatefain** [comment]
The positioning on these drop downs needs to be fixed.... The absolute positioning is all over the place depending on the screen size. My bad...

**Comment by alexgleason** [comment]
IMO the nav looks pretty good now!

![screenshot from 2017-11-27 14 15 18](https://user-images.githubusercontent.com/3639540/33284539-72db4c80-d37d-11e7-9adc-a7c1a24ca771.png)
