### ISSUE TITLE
Add a status and progress to order model

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#44]
I'm not sure exactly how this should be done, but there should be a way for us to pull a few pieces of data on an order into the front end. Some of these things I imagine would be done in the view, and some may need to be added to the model itself. 

1. Order is Open/Closed  (this can be generated from the dates)
2. Order status (OK/ something is wrong)
3. Order progress (possibly generated daily by comparing to reported harvests?)

There is a place in the templates already for each of these things, We just need to figure out the best way to generate the data itself so I can pull it in.

Screenshot for context:

![screenshot from 2017-11-30 14 27 12](https://user-images.githubusercontent.com/17955536/33450684-9b8b3cda-d5da-11e7-8ad6-595f5f140b52.png)

**Comment by alexgleason** [comment]
I don't think we need to base the progress bar on Harvests, just the dates. We can't know how many Harvests will occur for a certain order ahead of time, since Harvests occur at the discretion of the picker and are based on various things like weather conditions and when the crops were last harvested.

Instead we can just have it represent how many days have passed compared to the total. If the Order starts Dec 1 and ends Dec 10 it should be at 50% completion on Dec 5.

Also, the progress bar can serve the dual purpose of conveying whether the order is open/closed. A closed order either has a pull progress bar or something about it looks different.

**Comment by marykatefain** [comment]
Good points!
