### ISSUE TITLE
Add functionality to Edit and Cancel Order buttons

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#45]
These buttons should actually do these things. 

![screenshot from 2017-11-30 14 49 04](https://user-images.githubusercontent.com/17955536/33451838-346e2de2-d5de-11e7-8e19-2919376f863b.png)

**Comment by alexgleason** [comment]
Nice, the design looks great.

Edit Order should be pretty simple since it can mostly reuse the "new order" form.

Cancel Order has quite a few UI/UX considerations. @marykatefain, will you please read [Never Use a Warning When You Mean Undo](http://www.alistapart.com/articles/neveruseawarning/) and lmk your thoughts on how this applies here?

**Comment by marykatefain** [comment]
Will do! Thanks :)

**Comment by marykatefain** [comment]
Where did we land on this?

**Comment by alexgleason** [comment]
Still needs to be implemented.

**Comment by alexgleason** [comment]
I've let users cancel orders via 467a63d67cf79bc6ed25bb5e91f99f302c553777. I don't think we have time to let them "edit" orders for this milestone. They can cancel the order and then create a new order. It leaves a cleaner paper trail, and otherwise we'd need the ability to track the changes users make to their orders.
