### ISSUE TITLE
Allow users to edit more fields in their profile

### ISSUE THREAD

**Issue by marykatefain** [HarvestHub/GardenHub#73]
There is currently no place for users to actually upload their profile picture besides in the admin panel (which most people won't have access to). They should be able to do this from their Edit Profile page.

**Comment by marykatefain** [comment]
- [ ] Picture
- [ ] Email
- [ ] Phone number

**Comment by alexgleason** [comment]
Users can set their photo with b44c8ab9daa062d64a25097e5ba03dd4fdbaf4c6 now. We should probably review the [security implications](https://docs.djangoproject.com/en/2.0/topics/security/#user-uploaded-content-security) of this, however.

I'm a bit concerned about letting them change their email address because I don't know what exactly that would break. The email address is the username, so if anything relies on that it will be an issue. Can we let them change their email address in a future update? Worst case scenario, a user can make a new account with a different email address.

Phone number is also not simple, because we need some way to validate and normalize the phone number in the database. Thankfully, I found [django-phonenumber-field](https://github.com/stefanfoulis/django-phonenumber-field), but I'm concerned about adding a custom model field and relying on a package that doesn't have a big community support.

**Comment by marykatefain** [comment]
I think it's fine to hold off on email changes until a future update. Can we implement phone number without validation? I think the only thing that's important is that it's 9 characters long, only integers -yah? We don't need to confirm that the number they put it in is valid right now.

**Comment by JenniferGold** [comment]
Yes we can let them change their email address in another update.

For phone number who is adding this?  If only admins and managers as this
point then I could just be very careful and we could skip the
validation/normalization for now?  Even if users can edit this in their
profiles, worst case is they enter it slightly poorly in the free form
field?  Not sure what is best plan.

**Comment by alexgleason** [comment]
Closing in favor of #98 and #99
